name: github pages

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build-deploy:
    # This ensures that the `GITHUB_TOKEN` set in this GitHub Action job
    # has sufficient privileges to write to a secondary branch. On older
    # repositories, the `GITHUB_TOKEN` used to have lots of privileges,
    # but this needs to now be set explicitly. After setting this, people
    # can just fork `vast-www` and having a working deploy to the
    # `gh-pages` branch.
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - name: Timestamp Begin
        run: date

      - name: Clone VAST repo
        uses: actions/checkout@v3
        with:
          repository: trailofbits/vast
          ref: "master"
          submodules: true
          fetch-depth: 1
          path: ./vast

      - name: Install LLVM, Clang, MLIR
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 17 all && sudo apt-get install libmlir-17-dev mlir-17-tools

      - name: Get CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: 3.23.3

      - name: Configure CMake
        run: CC=clang-17 CXX=clang++-17 cmake --preset ninja-multi-default
          --toolchain ./cmake/lld.toolchain.cmake
          -DCMAKE_PREFIX_PATH=/usr/lib/llvm-17/
        working-directory: ./vast

      - name: Build VAST Dialect docs
        run: cmake --build --preset ninja-rel --target vast-doc
        working-directory: ./vast

      - name: Clone VAST WWW repo
        uses: actions/checkout@v3
        with:
          repository: trailofbits/vast-www
          ref: "main"
          fetch-depth: 1
          path: ./vast-www

      - name: Install VAST Dialect docs
        run: cp -rv ./vast/builds/ninja-multi-default/docs/ ./vast-www/docs/dialects/

      - name: Install VAST Source docs
        run: cp -rv ./vast/docs/* ./vast-www/docs/

      - name: Install MkDocs
        run: pip3 install mkdocs

      - name: Build Website
        run: mkdocs build
        working-directory: ./vast-www

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: trailofbits/vast
          publish_branch: gh-pages
          publish_dir: ./vast-www/site
          force_orphan: true
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"

      - name: Timestamp End
        run: date
